server {
  listen 80;
  server_name _;
  root /var/www/public;
  index index.php index.html;

  location / { try_files $uri $uri/ /index.php?$query_string; }

  location ~* \.(?:css|js|jpg|jpeg|png|gif|svg|webp|ico|woff2?)$ {
    try_files $uri =404;
    access_log off;
    expires 30d;
  }

  location ~ \.php$ {
    include /etc/nginx/fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    fastcgi_param DOCUMENT_ROOT $realpath_root;
    fastcgi_pass php:9000;   # ← php コンテナの 9000
    fastcgi_index index.php;
    fastcgi_read_timeout 180;
  }

  client_max_body_size 10M;
  sendfile on;
}
